### ISSUE TITLE
Error if connection is lost while adapter waits for anwer

### ISSUE THREAD

**Issue by braindead1** [braindead1/ioBroker.robonect#21]
> 2020-08-02 14:44:31.489 - error: robonect.0 (5567) Error: Error: connect ETIMEDOUT 192.168.171.67:80
2020-08-02 14:44:31.494 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2020-08-02 14:44:31.494 - error: robonect.0 (5567) unhandled promise rejection: Cannot read property 'status' of undefined
2020-08-02 14:44:31.496 - error: robonect.0 (5567) TypeError: Cannot read property 'status' of undefined
at Robonect. (/opt/iobroker/node_modules/iobroker.robonect/main.js:295:42)
at runMicrotasks ()
at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-08-02 14:44:32.094 - info: host.usv instance system.adapter.robonect.0 terminated with code 0 (NO_ERROR)
2020-08-02 14:44:32.099 - info: host.usv Restart adapter system.adapter.robonect.0 because enabled

**Comment by bjoernbusch** [comment]
I'm seeing the same issue, anything that can be done about that?

**Comment by bjoernbusch** [comment]
ok, found in the forum the hint that the password for the mower should not contain special characters, now it works.
