### ISSUE TITLE
It is not possible to start an instance

### ISSUE THREAD

**Issue by sonneimtal** [braindead1/ioBroker.robonect#31]
![image](https://user-images.githubusercontent.com/23382426/164205403-20405080-30c2-4423-869a-6bbb3b1f7d0b.png)

**Comment by Alkodemiker** [comment]
Had the same issue, changed my password to "letters only" no special characters. Then it worked

**Comment by savek-cc** [comment]
Just performed a clean install - configured and started without issue.

**Comment by sonneimtal** [comment]
2022-05-31 07:12:48.002 - info: host.nuc-iobroker "system.adapter.robonect.0" enabled
--
2022-05-31 07:12:48.027 - info: host.nuc-iobroker instance system.adapter.robonect.0 started with pid 579172
2022-05-31 07:12:49.011 - info: robonect.0 (579172) starting. Version 0.1.4 in /opt/iobroker/node_modules/iobroker.robonect, node: v14.19.1, js-controller: 4.0.21
2022-05-31 07:12:49.030 - info: robonect.0 (579172) Rest period 1 not configured. Period will be ignored.
2022-05-31 07:12:49.031 - info: robonect.0 (579172) Rest period 2 not configured. Period will be ignored.
2022-05-31 07:12:50.061 - info: robonect.0 (579172) Done
2022-05-31 07:12:50.088 - error: robonect.0 (579172) Error: Error: getaddrinfo EAI_AGAIN ralf
2022-05-31 07:12:50.090 - error: robonect.0 (579172) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2022-05-31 07:12:50.090 - error: robonect.0 (579172) unhandled promise rejection: Cannot read property 'status' of undefined
2022-05-31 07:12:50.091 - error: robonect.0 (579172) TypeError: Cannot read property 'status' of undefined
at Robonect. (/opt/iobroker/node_modules/iobroker.robonect/main.js:283:42)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-05-31 07:12:50.091 - error: robonect.0 (579172) Cannot read property 'status' of undefined
2022-05-31 07:12:50.097 - info: robonect.0 (579172) cleaned everything up...
2022-05-31 07:12:50.098 - info: robonect.0 (579172) terminating
2022-05-31 07:12:50.098 - warn: robonect.0 (579172) Terminated (UNCAUGHT_EXCEPTION): Without reason
2022-05-31 07:12:50.653 - error: host.nuc-iobroker instance system.adapter.robonect.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2022-05-31 07:12:50.653 - info: host.nuc-iobroker Restart adapter system.adapter.robonect.0 because enabled
2022-05-31 07:12:54.249 - info: host.nuc-iobroker "system.adapter.robonect.0" disabled


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by sonneimtal** [comment]
The problem is the password with special characters, with an unsafe password it will run
